<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	  <LangVersion>latest</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="DTOs\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Adhe.Core\Core.SharedServices\Core.SharedServices.csproj" />
    <ProjectReference Include="..\Questioner.Repository\Questioner.Repository.csproj" />
  </ItemGroup>

</Project>
